### ISSUE TITLE
NameError: 'TICKS_PER_ROTATION' is an invalid field name.  It should have   the pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'

### ISSUE THREAD

**Issue by enekaa** [norlab-ulaval/norlab_custom_interfaces#1]
Hi! 

We are a team working with robotics in digital arts and experimental media from the University of Washington installing your Roboclaw driver (thanks!) We have noticed that norlab_custom_interfaces is necessary to run the Roboclaw driver. Inside my ~/ros2_ws/src/ directory I have:

`git clone https://github.com/norlab-ulaval/norlab_custom_interfaces.git
`
And then in ~/ros2_ws/, I run "colcon build". This is when I receive the error:

```
NameError: 'TICKS_PER_ROTATION' is an invalid field name.  It should have
  the pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'
```
In EncoderState.msg, according to the error message, TICKS_PER_ROTATION and TICKS_PER_METER can't be in uppercase. Changing them to lower caps fixes the error when trying to launch the Roboclaw node. However, we can only launch the Roboclaw node with parameters publish_encoders and publish_elec set to False < otherwise, we get other error messages that I suspect could be related to messing with the above .msg file.

Edit: these were the error messages we were getting when publish_encoders or publish_elec were set to True:

```
[roboclaw_node-1] python3: ./.obj-aarch64-linux-gnu/rosidl_generator_py/std_msgs/msg/_float32_s.c:50: std_msgs__msg__float32__convert_from_py: Assertion strncmp("std_msgs.msg._float32.Float32", full_classname_dest, 29) == 0' failed.
[ERROR] [roboclaw_node-1]: process has died [pid 10214, exit code -6, cmd 
```

This error in ROS2 Humble is more understandable: something similar to "velocity expected to be of type Float32."

We are running ROS2 Jazzy in Ubuntu 24.04 on Raspberry Pi 5 8GB. 

I (team lead) am an artist, not a programmer, but I learn fast! Apologies for formatting if wrong.

**Comment by enekaa** [comment]
UPDATE: after countless hours of debugging, the solution was somewhat simple:

MotorState.msg should be

```
std_msgs/Header header
float32 current          # (A)
float32 voltage          # (V)
float32 duty             # (%)
float32 temperature      # (C) new addition
```

And EncoderState.msg should be

```
std_msgs/Header header
float32 position             # (ticks)
float32 velocity             # (ticks/sec) originally: speed
float32 ticks_per_rotation   # originally: TICKS_PER_ROTATION
float32 ticks_per_meter      # originally: TICKS_PER_METER
```

This solves all publishing errors that occurred launching the roboclaw_ros driver.
Edit: correction requests (pull requests?) have been proposed

**Comment by pomerlef** [comment]
@IamPhytan , can you have a look?

**Comment by IamPhytan** [comment]
Hi @enekaa,

Glad to know that our driver is useful for you :smile: 

I found out that we debugged the interfaces on our robot, but the changes were not committed nor pushed on GitHub.
I just pushed those changes, which are exactly those that you posted in your reply.

Have a nice day
